server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          uri: git@github.com-vicente:vicente96074/afaas.git
          default-label: main
          search-paths: config-data
          private-key: ${SSH_GITHUB_OWNER_PRIVATE_KEY}
  application:
    name: config-service